name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    strategy:
        matrix:
          vm-os: [ubuntu-latest, macOS-latest, windows-latest]
          go-version: [1.14, 1.15, 1.16]
    runs-on: ubuntu-latest
    steps:
 
    - name: Install go ${{ matrix.go-version }} 
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Install dependencies
      uses: actions/checkout@v2

    - name: Test and create coverage file
      run: go test -coverprofile=coverage.txt -covermode=atomic

    - name: Upload coverage file to codecov
      uses: codecov/codecov-action@v1
      with:
          token: ${{secrets.CODECOV_TOKEN}}
