name: test

on:
  push:
    branches: [ develop,master ]
  pull_request:
    branches: [ develop,master ]
env:
  TZ: "PRC"
jobs:

  test:
    strategy:
      matrix:
        vm-os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.vm-os }}
    env:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
    steps:
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.16.0'
          
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create coverage file
        run: go test -coverprofile='coverage.txt' -covermode=atomic

      - name: Upload coverage file
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}
